#!/usr/bin/env bash
# UserPromptSubmit hook: relay one-shot flags into `additionalContext`.
#   .usage-flag   (usage-monitor.sh)  -> auto-save directive
#   .compact-flag (pre-compact hook)  -> compaction-happened notice
#
# Flags are one-shot: removed after read.
#
# Output: JSON to stdout per Claude Code UserPromptSubmit hook contract.
# Silent (exit 0, no output) if no flag is present.

set -e

DIR=".claude/handoff"
FLAG_FILE="$DIR/.usage-flag"
COMPACT_FLAG="$DIR/.compact-flag"
MSG=""

# --- usage flag ---
if [ -f "$FLAG_FILE" ]; then
  # Atomically claim the flag: rename it so usage-monitor can't write a new
  # flag in the same name and have it lost. mv is atomic on the same
  # filesystem; if the rename loses (file vanished), continue without it.
  CLAIMED="$FLAG_FILE.claimed.$$"
  if mv "$FLAG_FILE" "$CLAIMED" 2>/dev/null; then
    FLAG=$(cat "$CLAIMED" 2>/dev/null || true)
    rm -f "$CLAIMED" 2>/dev/null || true

    # Parse flag: "AUTO_SAVE:92" or "URGENT:96"
    TYPE="${FLAG%%:*}"
    PERCENT="${FLAG##*:}"

    # Build per-tier message.
    # (Plain ASCII to avoid cross-platform parser/encoding issues; the per-language
    # user-facing phrasing is generated by Claude per SKILL.md Mode 1c.)
    case "$TYPE" in
      URGENT)
        MSG="CRITICAL: 5-hour usage at ${PERCENT} percent. IMMEDIATELY auto-save a handoff before answering the user. Run the SAVE flow (extract-recent-files then write handoff to .claude/handoff/current.md then finalize-handoff). Do NOT ask the user. After save completes, briefly notify them in their language (see Mode 1c URGENT row in SKILL.md for per-language phrasing) then handle their original request. If finalize-handoff fails after 2 retries, warn the user and continue anyway."
        ;;
      AUTO_SAVE)
        MSG="5-hour usage at ${PERCENT} percent. Auto-save a handoff before answering the user. Run the SAVE flow (extract-recent-files then write handoff then finalize-handoff). Do NOT ask the user. After save, briefly notify them in their language (see Mode 1c AUTO_SAVE row in SKILL.md for per-language phrasing) then handle their request."
        ;;
    esac
  fi
fi

# --- compact flag (one-shot) ---
if [ -f "$COMPACT_FLAG" ]; then
  CCLAIMED="$COMPACT_FLAG.claimed.$$"
  if mv "$COMPACT_FLAG" "$CCLAIMED" 2>/dev/null; then
    rm -f "$CCLAIMED" 2>/dev/null || true
    CMSG="NOTICE: a context compaction (/compact) occurred before this prompt. Pre-compact details now exist only in compressed form. If .claude/handoff/current.md was saved BEFORE the compaction, treat it as the authoritative pre-compact record - do NOT overwrite it from post-compact memory without the user's confirmation (suggest /handoff-revive:preview to review it first). Saving new post-compact work is fine."
    if [ -n "$MSG" ]; then
      MSG="$MSG

$CMSG"
    else
      MSG="$CMSG"
    fi
  fi
fi

if [ -z "$MSG" ]; then
  exit 0
fi

# --- JSON-escape the message (pure bash) ---
json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\b'/\\b}"
  s="${s//$'\f'/\\f}"
  s="${s//$'\r'/\\r}"
  s="${s//$'\t'/\\t}"
  s="${s//$'\n'/\\n}"
  printf '"%s"' "$s"
}

ESC=$(json_escape "$MSG")

# Emit JSON. UserPromptSubmit honors hookSpecificOutput.additionalContext.
printf '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":%s}}\n' "$ESC"

exit 0
